USE `mispdb`;
INSERT INTO `s_system_function_set`(FUNCTION_ID,FUNCTION_NAME,FUNCTION_TYPE,FUNCTION_DESP) VALUES ("1",'系统配置',NULL,'进行系统配置');
INSERT INTO `s_system_function_set`(FUNCTION_ID,FUNCTION_NAME,FUNCTION_TYPE,FUNCTION_DESP) VALUES ("2",'用户管理',NULL,'进行系统配置');
INSERT INTO `s_system_function_set`(FUNCTION_ID,FUNCTION_NAME,FUNCTION_TYPE,FUNCTION_DESP) VALUES ("3",'用户组管理',NULL,'进行系统配置');
INSERT INTO `s_system_function_set`(FUNCTION_ID,FUNCTION_NAME,FUNCTION_TYPE,FUNCTION_DESP) VALUES ("4",'组织机构管理',NULL,'进行系统配置');
INSERT INTO `s_system_function_set`(FUNCTION_ID,FUNCTION_NAME,FUNCTION_TYPE,FUNCTION_DESP) VALUES ("5",'个人设置',NULL,'进行系统配置');
INSERT INTO `s_system_function_set`(FUNCTION_ID,FUNCTION_NAME,FUNCTION_TYPE,FUNCTION_DESP) VALUES ("6",'信息/密码修改',NULL,'进行系统配置');

 





