

USE `mispdb`;

 
INSERT INTO `d_system_id_type`(NAME,STEP,LENGTH,INC_MODE,CURRENT_ID,PREFIX,SUFFIX) VALUES ("ORG_ID",1,10,1,10000,NULL,NULL);
INSERT INTO `d_system_id_type`(NAME,STEP,LENGTH,INC_MODE,CURRENT_ID,PREFIX,SUFFIX) VALUES ("USER_GROUP_ID",1,10,1,10000,NULL,NULL);
 