USE `mispdb`;
INSERT INTO `d_GROUP`(GROUP_ID,GROUP_NAME,GROUP_DESP) VALUES ("1",'管理员','完成管理工作');
INSERT INTO `d_GROUP`(GROUP_ID,GROUP_NAME,GROUP_DESP) VALUES ("11",'部门领导','监控，审批工作');
INSERT INTO `d_GROUP`(GROUP_ID,GROUP_NAME,GROUP_DESP) VALUES ("111",'员工','实施具体工作');
INSERT INTO `d_GROUP`(GROUP_ID,GROUP_NAME,GROUP_DESP) VALUES ("112",'外包','实施具体工作');






