USE `mispdb`;

INSERT INTO `s_system_meta_data` (`TABLE_NAME`,`ATTR_NAME`,`ATTR_DEFAULT_VALUE`,`IS_DISPLAY`,`IS_FILTER`,`SORT_ORDER`) VALUES ('D_USER_EXT_ATTR','AGE',NULL,1,1,1);
INSERT INTO `s_system_meta_data` (`TABLE_NAME`,`ATTR_NAME`,`ATTR_DEFAULT_VALUE`,`IS_DISPLAY`,`IS_FILTER`,`SORT_ORDER`) VALUES ('D_USER_EXT_ATTR','BIRTHDAY',NULL,1,1,2);
INSERT INTO `s_system_meta_data` (`TABLE_NAME`,`ATTR_NAME`,`ATTR_DEFAULT_VALUE`,`IS_DISPLAY`,`IS_FILTER`,`SORT_ORDER`) VALUES ('D_USER_EXT_ATTR','EMAIL','tangjun@fuego.cn',1,1,3);

 




